server {
    listen       80;
    server_name  iaemp.demo.xify.in;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ =404;
    }

    # Optimization for images/static assets
    location ~* \.(png|jpg|jpeg|gif|webp|ico|svg|css|js)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
